### ISSUE TITLE
为什么不把节点objID存数据呢，而是多一个int

### ISSUE THREAD

**Issue by weisd** [XanthusL/zset#2]
为什么不把节点objID存数据呢，而是多一个int

**Comment by XanthusL** [comment]
应该是可以直接把数据放到节点上的。现在是节点上只有数据的id跟用于比较的分值，数据统一放到哈希了。当时直接照搬redis的zset，具体实现也没有考虑哪种方式最适合go。
可以来个benchmark，看看哪种方式更好一些。欢迎PR
