### ISSUE TITLE
可以处理下并列名次吗？

### ISSUE THREAD

**Issue by 15951836388** [XanthusL/zset#3]
感谢作者，很好用。

相同分数的，可以实现并列名次吗？

**Comment by XanthusL** [comment]
这个是之前为游戏中排行榜做的，直接“复刻”redis中的zset。

目前实现的这几个特性都是必需的，还有一些没有实现

我觉得可以稍微封装一下`zslFirstInRange`和`zslLastInRange`来实现某些场景下的“并列”，但在跳表中的数据实际上仍不是并列。

另外，一直在犹豫要不要把key改成字符串，虽然多数时候比int64占空间，但是更通用。也不知道泛型得等到什么时候。

最近比较忙，近期不会更新这个，欢迎PR

**Comment by 15951836388** [comment]
用string作为唯一id的比较少
