### ISSUE TITLE
如何实现多条件排序

### ISSUE THREAD

**Issue by 15951836388** [XanthusL/zset#4]
比如战斗力相同的情况下，再按等级排，等级相同，再按境界排。

请问这类需求，应该如何实现？

**Comment by XanthusL** [comment]
当前版本是按照Redis，根据一个浮点型的值作为判断分值。
可以将多个条件组合成一个分值, 例如
```
// 假设等级范围是[0,100), 境界范围是[0,10), 
// 不考虑溢出
score  = 战力 * 1000 + 等级 * 10 + 境界
```
可以将比较的分值改为接口，这样比较起来灵活。但是无法根据分值查找

**Comment by 15951836388** [comment]
恩，我改借口。游戏，一般没有按分值查询的需求

**Comment by 15951836388** [comment]
@XanthusL 

考虑是用接口，还是像官方sort那样传入一个排序方法方便？

**Comment by XanthusL** [comment]
需要把所有比较`score`的地方都换掉。
