### ISSUE TITLE
你好，可否增加increaseby功能

### ISSUE THREAD

**Issue by xcl3721** [XanthusL/zset#5]
你好，可否增加increaseby功能
set方式需要先加锁
get内容
然后+1或者+n
set回去

**Comment by xcl3721** [comment]
以及getrank是否能够增加列表获取功能
如getrankbylimit

**Comment by XanthusL** [comment]
> 你好，可否增加increaseby功能
> set方式需要先加锁
> get内容
> 然后+1或者+n
> set回去

这个跳表不是并发安全的，需要加锁。而且目前为了简化实现，用一个map存放数据，并发情况下也是需要加锁的。
`lock-free`的实现过于复杂暂不考虑。移除了之前`SortedSet`内置的锁就是为了避免一次性多次操作的场景下反复加锁、解锁的情况。
没有内置锁，用的时候需要自己加锁，麻烦一些。不过可以更灵活地控制锁的粒度

**Comment by xcl3721** [comment]
> > 你好，可否增加increaseby功能
> > set方式需要先加锁
> > get内容
> > 然后+1或者+n
> > set回去
> 
> 这个跳表不是并发安全的，需要加锁。而且目前为了简化实现，用一个map存放数据，并发情况下也是需要加锁的。
> `lock-free`的实现过于复杂暂不考虑。移除了之前`SortedSet`内置的锁就是为了避免一次性多次操作的场景下反复加锁、解锁的情况。
> 没有内置锁，用的时候需要自己加锁，麻烦一些。不过可以更灵活地控制锁的粒度

非常感谢！getrank列表功能是否考虑添加？

**Comment by XanthusL** [comment]
Redis 有序集合的所有命令对应的功能都在计划中，但最近比较忙

**Comment by xcl3721** [comment]
新功能发现加锁后
2019/05/31 14:16:02 http: panic serving 127.0.0.1:60733: runtime error: invalid memory address or nil pointer dereference
goroutine 339 [running]:
net/http.(*conn).serve.func1(0xc00025e0a0)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:1769 +0xc9
panic(0x12943a0, 0x151c510)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/panic.go:522 +0x1b5
github.com/XanthusL/zset.(*skipList).zslInsert(0xc00000e060, 0x40de140000000000, 0x4d0, 0x1)
	/Users/changlong.xu/go/pkg/mod/github.com/!xanthus!l/zset@v0.0.0-20190530061537-58641c2063e1/zset.go:172 +0x36a
github.com/XanthusL/zset.(*SortedSet).IncrBy(0xc000406c40, 0x4069000000000000, 0x4d0, 0x4, 0xc00012e088, 0x102c241)
	/Users/changlong.xu/go/pkg/mod/github.com/!xanthus!l/zset@v0.0.0-20190530061537-58641c2063e1/zset.go:536 +0xfa
main.incrScore(0x12e6df6, 0x4, 0x4d0, 0x4069000000000000, 0x12e6c2a, 0x3)
	/Users/changlong.xu/vagrant/share/golang/Bifrost/src/main.go:69 +0xe7
main.addTop(0x13483a0, 0xc0003fd340, 0xc000468b00)
	/Users/changlong.xu/vagrant/share/golang/Bifrost/src/main.go:91 +0x7b
net/http.HandlerFunc.ServeHTTP(0x12faf00, 0x13483a0, 0xc0003fd340, 0xc000468b00)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1527ca0, 0x13483a0, 0xc0003fd340, 0xc000468b00)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00009ec30, 0x13483a0, 0xc0003fd340, 0xc000468b00)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc00025e0a0, 0x1348920, 0xc000279000)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2884 +0x2f4

**Comment by XanthusL** [comment]
不加锁并发会这样。是不是没锁上，具体用法方便贴一下么

**Comment by xcl3721** [comment]
package main

import (
	"github.com/XanthusL/zset"
	"sync"
	"net/http"
	"log"
)

//an lock for map operate
var sortSetListLock sync.RWMutex

//set name and sort list
var sortSetListMap map[string]sortSetInfoObj

type (
	/*
		sort set map info obj
	 */
	sortSetInfoObj struct {
		Key       string
		SortSet   zset.SortedSet
		SortType  int16
		Lock      sync.RWMutex //可能取消掉
		TaskQueue chan string  //任务队列
	}
)

func init() {
	//init map for list
	sortSetListLock.Lock()
	sortSetListMap = make(map[string]sortSetInfoObj)
	sortSetListLock.Unlock()

	//sortset = zset.New()
}

func checkHaveMap(mapKey string) {
	//check the map already exist?
	if _, ok := sortSetListMap[mapKey]; !ok {

		//not have
		//start lock to create
		sortSetListLock.Lock()

		//check again not have
		if _, ok1 := sortSetListMap[mapKey]; !ok1 {

			//create an new zset
			var infoObj sortSetInfoObj

			infoObj.Key = mapKey
			infoObj.SortSet = *zset.New()
			infoObj.SortType = 0 //todo:type define
			infoObj.TaskQueue = make(chan string, 1000)
			sortSetListMap[mapKey] = infoObj
		}
		sortSetListLock.Unlock()
	}
}

func incrScore(mapKey string, key int64, score float64, data string) {

	//increse score
	var mapObj = sortSetListMap[mapKey]

	mapObj.Lock.Lock()

	sc, ok := mapObj.SortSet.IncrBy(score, key)

	//not exist create one
	if sc == 0 && ok == nil {
		mapObj.SortSet.Set(score, key, data)
	}

	mapObj.Lock.Unlock()
	//todo: create go coro

}

func addTop(w http.ResponseWriter, r *http.Request) {

	var mapKey string = "test"; //todo:parameter
	var score float64 = 200.0;  //todo:parameter
	var key int64 = 1232;       //todo:parameter
	var data string = "yes";    //todo:parameter

	//check sort set exist and create
	checkHaveMap(mapKey)

	//incrScore
	incrScore(mapKey, key, score, data)
}

func getTop(w http.ResponseWriter, r *http.Request) {

}

func main() {

	//fmt.Println("length is ", sortset.Length())
	http.HandleFunc("/addtop", addTop)
	http.HandleFunc("/gettop", getTop)

	err := http.ListenAndServe(":9229", nil)
	if err != nil {
		log.Fatal("Listen Server Fail: ", err)
		return
	}
}

/*
func addTop(w http.ResponseWriter, r *http.Request) {
	//request, err := ioutil.ReadAll(r.Body)
	//if (err != nil) {
	//	return
	//}

	//json.Unmarshal(request, xxxx)

	mutex.Lock()
	atomic.AddInt64(&idcount, 1)

	sortset.Set(float64(idcount), idcount, "yesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyes")
	mutex.Unlock()

	w.Write([]byte("ok"));
}

func getTop(w http.ResponseWriter, r *http.Request) {
	mutex.Lock()
	var buffer bytes.Buffer

	for i := int64(0); i < sortset.Length(); i++ {
		id, score, extra := sortset.GetDataByRank(int64(i), true)
		buffer.WriteString("id:" + strconv.FormatInt(id, 10))
		buffer.WriteString(" sc:" + strconv.FormatFloat(score, 'E', -1, 64))
		buffer.WriteString(" ext:" + extra.(string))
		buffer.WriteString("\r\n")
	}
	w.Write(buffer.Bytes())

	mutex.Unlock()

}

func main() {

	for i := 0; i < 4000000; i++ {
		s.Set(float64(1232 + i), int64(i), "yes")
		if (i % 1000000) == 0 {
			fmt.Println("now is ",i)
		}
	}

	fmt.Println("length is ", sortset.Length())
	http.HandleFunc("/settop", addTop)
	http.HandleFunc("/gettop", getTop)

	err := http.ListenAndServe(":9229", nil)
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
	}
}
*/

**Comment by xcl3721** [comment]
`
package main

import (
	"github.com/XanthusL/zset"
	"sync"
	"net/http"
	"log"
)

//an lock for map operate
var sortSetListLock sync.RWMutex

//set name and sort list
var sortSetListMap map[string]sortSetInfoObj

type (
	/*
		sort set map info obj
	 */
	sortSetInfoObj struct {
		Key       string
		SortSet   zset.SortedSet
		SortType  int16
		Lock      sync.RWMutex //可能取消掉
		TaskQueue chan string  //任务队列
	}
)

func init() {
	//init map for list
	sortSetListLock.Lock()
	sortSetListMap = make(map[string]sortSetInfoObj)
	sortSetListLock.Unlock()

	//sortset = zset.New()
}

func checkHaveMap(mapKey string) {
	//check the map already exist?
	if _, ok := sortSetListMap[mapKey]; !ok {

		//not have
		//start lock to create
		sortSetListLock.Lock()

		//check again not have
		if _, ok1 := sortSetListMap[mapKey]; !ok1 {

			//create an new zset
			var infoObj sortSetInfoObj

			infoObj.Key = mapKey
			infoObj.SortSet = *zset.New()
			infoObj.SortType = 0 //todo:type define
			infoObj.TaskQueue = make(chan string, 1000)
			sortSetListMap[mapKey] = infoObj
		}
		sortSetListLock.Unlock()
	}
}

func incrScore(mapKey string, key int64, score float64, data string) {

	//increse score
	var mapObj = sortSetListMap[mapKey]

	mapObj.Lock.Lock()

	sc, ok := mapObj.SortSet.IncrBy(score, key)

	//not exist create one
	if sc == 0 && ok == nil {
		mapObj.SortSet.Set(score, key, data)
	}

	mapObj.Lock.Unlock()
	//todo: create go coro

}

func addTop(w http.ResponseWriter, r *http.Request) {

	var mapKey string = "test"; //todo:parameter
	var score float64 = 200.0;  //todo:parameter
	var key int64 = 1232;       //todo:parameter
	var data string = "yes";    //todo:parameter

	//check sort set exist and create
	checkHaveMap(mapKey)

	//incrScore
	incrScore(mapKey, key, score, data)
}

func getTop(w http.ResponseWriter, r *http.Request) {

}

func main() {

	//fmt.Println("length is ", sortset.Length())
	http.HandleFunc("/addtop", addTop)
	http.HandleFunc("/gettop", getTop)

	err := http.ListenAndServe(":9229", nil)
	if err != nil {
		log.Fatal("Listen Server Fail: ", err)
		return
	}
}

/*
func addTop(w http.ResponseWriter, r *http.Request) {
	//request, err := ioutil.ReadAll(r.Body)
	//if (err != nil) {
	//	return
	//}

	//json.Unmarshal(request, xxxx)

	mutex.Lock()
	atomic.AddInt64(&idcount, 1)

	sortset.Set(float64(idcount), idcount, "yesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyesyes")
	mutex.Unlock()

	w.Write([]byte("ok"));
}

func getTop(w http.ResponseWriter, r *http.Request) {
	mutex.Lock()
	var buffer bytes.Buffer

	for i := int64(0); i < sortset.Length(); i++ {
		id, score, extra := sortset.GetDataByRank(int64(i), true)
		buffer.WriteString("id:" + strconv.FormatInt(id, 10))
		buffer.WriteString(" sc:" + strconv.FormatFloat(score, 'E', -1, 64))
		buffer.WriteString(" ext:" + extra.(string))
		buffer.WriteString("\r\n")
	}
	w.Write(buffer.Bytes())

	mutex.Unlock()

}

func main() {

	for i := 0; i < 4000000; i++ {
		s.Set(float64(1232 + i), int64(i), "yes")
		if (i % 1000000) == 0 {
			fmt.Println("now is ",i)
		}
	}

	fmt.Println("length is ", sortset.Length())
	http.HandleFunc("/settop", addTop)
	http.HandleFunc("/gettop", getTop)

	err := http.ListenAndServe(":9229", nil)
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
	}
}
*/

`

**Comment by xcl3721** [comment]
ab -c 100 -n 1000000 "http://127.0.0.1:9229/addtop"

**Comment by XanthusL** [comment]
@xcl3721 `sync.RWMutex`用法不对
```
// A RWMutex must not be copied after first use.
```
`sortSetListMap`的类型是`map[string]sortSetInfoObj`,这样每次都会把锁拷贝了。
应该用 `map[string]*sortSetInfoObj`。
或者`sorSetInfoObj.Lock`换成指针

**Comment by xcl3721** [comment]
> @xcl3721 `sync.RWMutex`用法不对
> 
> ```
> // A RWMutex must not be copied after first use.
> ```
> 
> `sortSetListMap`的类型是`map[string]sortSetInfoObj`,这样每次都会把锁拷贝了。
> 应该用 `map[string]*sortSetInfoObj`。
> 或者`sorSetInfoObj.Lock`换成指针

不好意思，给你添麻烦了，尴尬

**Comment by xcl3721** [comment]
代码删除掉了。。。公司用。。

**Comment by xcl3721** [comment]
测试成功，性能很好！
